### ISSUE TITLE
Delete cause only if not used in a disruption

### ISSUE THREAD

**Issue by vpassama** [CanalTP/Chaos#180]
Hi,

I've got a problem with cause deletion in chaos. I'm able to delete a cause even if it is used by a disruption. It leads to errors in our 'realtime-like' interface when I want to edit a disruption with a 'deleted' cause.

In our interface, when I get the edition form of the disruption, I build a html select input with all available causes for the disruption. If the disruption is linked to a 'deleted' cause (is_visible = false) I won't be able to add the id in the select input because the cause won't appear in the get /causes.

Should'nt be wiser to check the cause is not linked to a 'published' (or 'draft') disruption before deleting it ?

I know I could add 'by hand' the id in the available list but I think a check is cleaner.

**Comment by eturck** [comment]
Have you had the time to discuss it internally?
If needed we're open to discuss it further, and if it's really the expected behavior we would be able to add those constraints somewhere else. It's just that we would prefer to contribute to chaos if it's something wanted instead of implementing it just into our soft.

**Comment by VirginieSchmidt** [comment]
Hi, this issue has been on hold lately, we are still discussing it. I'll come back to you with more information tomorrow.
